name: CI/CD for Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/single-loyalty-platform/cloud-run-revenues-ingest-bigquery:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy cloud-run-revenues-ingest-bigquery \                 
    --source . \                                                        
    --platform managed \                            
    --region asia-southeast1 \                                          
    --allow-unauthenticated \                                                                     
    --set-env-vars PROJECT_ID=single-loyalty-platform,DATASET_ID=slp_grading_lz,BUCKET_NAME=slp-landing-bucket,TABLE_NAME=slp_grade_revenues,PREFIX_NAME_ST=slp-grading,PREFIX_NAME_ND=revenues





